/* POKEMON */

export const SET_POKEMON = "SET_POKEMON"
export const SET_POKEMON_LOADING = "SET_POKEMON_LOADING"
export const SET_POKEMON_FAIL = "SET_POKEMON_FAIL"


/* ABILITIES */
export const SET_ABILITY = "SET_ABILITY"
export const SET_ABILITY_FAIL = "SET_ABILITY_FAIL"
 

/* BERRIES */
export const SET_BERRIES = "SET_BERRIES"
export const SET_BERRIES_FAIL = "SET_BERRIES_FAIL"
export const BERRIES_CONNECT ="BERRIES_CONNECT"

/* EVOLUTIONS */
export const SET_EVOLUTIONS = "SET_EVOLUTIONS"
export const SET_EVOLUTIONS_FAIL = "SET_EVOLUTIONS_FAIL"
export const EVOLUTIONS_CONNECT ="EVOLUTIONS_CONNECT"


/* MOVES */
export const SET_MOVES = "SET_MOVES"
export const SET_MOVES_FAIL = "SET_MOVES_FAIL"
export const MOVES_CONNECT ="MOVES_CONNECT"


/* ENCOUNTERS */
export const SET_ENCOUNTERS = "SET_ENCOUNTERS"
export const SET_ENCOUNTERS_FAIL = "SET_ENCOUNTERS_FAIL"
export const ENCOUNTERS_CONNECT ="ENCOUNTERS_CONNECT"


/* ITEMS */
export const SET_ITEMS = "SET_ITEMS"
export const SET_ITEMS_FAIL = "SET_ITEMS_FAIL"
export const ITEMS_CONNECT ="ITEMS_CONNECT"


/* GAMES */
export const SET_GAMES = "SET_GAMES"
export const SET_GAMES_FAIL = "SET_GAMES_FAIL"
export const GAMES_CONNECT ="GAMES_CONNECT"

/* LOCATIONS */
export const SET_LOCATIONS = "SET_LOCATIONS"
export const SET_LOCATIONS_FAIL = "SET_LOCATIONS_FAIL"
export const LOCATIONS_CONNECT ="LOCATIONS_CONNECT"