/* POKEMON */

export const SET_POKEMON = "SET_POKEMON"
export const SET_POKEMON_LOADING = "SET_POKEMON_LOADING"
export const SET_POKEMON_FAIL = "SET_POKEMON_FAIL"


/* ABILITIES */
export const SET_ABILITY = "SET_ABILITY"
export const SET_ABILITY_FAIL = "SET_ABILITY_FAIL"
export const SET_ABILITIES_LOADING = "SET_ABILITIES_LOADING"
 

/* BERRIES */
export const SET_BERRIES = "SET_BERRIES"
export const SET_BERRIES_FAIL = "SET_BERRIES_FAIL"
export const SET_BERRIES_LOADING ="BERRIES_LOADING"


/* EVOLUTIONS */
export const SET_EVOLUTIONS = "SET_EVOLUTIONS"
export const SET_EVOLUTIONS_FAIL = "SET_EVOLUTIONS_FAIL"
export const SET_EVOLUTIONS_LOADING ="EVOLUTIONS_LOADING"


/* MOVES */
export const SET_MOVES = "SET_MOVES"
export const SET_MOVES_FAIL = "SET_MOVES_FAIL"
export const SET_MOVES_LOADING ="MOVES_LOADING"


/* NATURES */
export const SET_NATURES = "SET_NATURES"
export const SET_NATURES_FAIL = "SET_NATURES_FAIL"
export const SET_NATURES_LOADING ="NATURES_LOADING"


/* ITEMS */
export const SET_ITEMS = "SET_ITEMS"
export const SET_ITEMS_FAIL = "SET_ITEMS_FAIL"
export const SET_ITEMS_LOADING ="ITEMS_LOADING"


/* GAMES */
export const SET_GAMES = "SET_GAMES"
export const SET_GAMES_FAIL = "SET_GAMES_FAIL"
export const SET_GAMES_LOADING ="GAMES_LOADING"

/* LOCATIONS */
export const SET_LOCATIONS = "SET_LOCATIONS"
export const SET_LOCATIONS_FAIL = "SET_LOCATIONS_FAIL"
export const SET_LOCATIONS_LOADING ="LOCATIONS_LOADING"


/* STREAM */

export const SET_STREAM ="SET_STREAM"