/* POKEMON */

export const SET_POKEMON = "SET_POKEMON"
export const SET_POKEMON_LOADING = "SET_POKEMON_LOADING"
export const SET_POKEMON_FAIL = "SET_POKEMON_FAIL"


/* ABILITIES */
export const SET_ABILITY = "SET_ABILITY"
export const SET_ABILITY_FAIL = "SET_ABILITY_FAIL"
 

/* BERRIES */
export const SET_BERRIES = "SET_BERRIES"
export const SET_BERRIES_FAIL = "SET_BERRIES_FAIL"
export const BERRIES_CONNECT ="BERRIES_CONNECT"

/* EVOLUTIONS */